name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '🚀 Features'
    labels:
      - 'type: feature'
      - 'enhancement'
      - 'feat'
  - title: '🐛 Bug Fixes'
    labels:
      - 'type: bug'
      - 'fix'
      - 'bugfix'
  - title: '🧰 Maintenance'
    labels:
      - 'type: maintenance'
      - 'chore'
      - 'dependencies'
  - title: '📚 Documentation'
    labels:
      - 'documentation'
      - 'docs'
  - title: '🔧 Performance'
    labels:
      - 'performance'
      - 'perf'
  - title: '🛡️ Security'
    labels:
      - 'security'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
  major:
    labels:
      - 'major'
      - 'breaking'
      - 'type: breaking'
  minor:
    labels:
      - 'minor'
      - 'feature'
      - 'type: feature'
      - 'enhancement'
      - 'feat'
  patch:
    labels:
      - 'patch'
      - 'fix'
      - 'bugfix'
      - 'type: bug'
      - 'chore'
      - 'dependencies'
      - 'documentation'
      - 'docs'
  default: patch
template: |
  ## Changes

  $CHANGES
  
  ## Installation
  
  Download the appropriate binary for your platform from the assets below.
  
  ### Using Cargo
  
  ```bash
  cargo install fast-tts-cli
  ```
  
  ### Direct Download
  
  - **Linux (x86_64)**: `fast-tts-cli-x86_64-unknown-linux-gnu.tar.gz`
  - **Linux (ARM64)**: `fast-tts-cli-aarch64-unknown-linux-gnu.tar.gz`
  - **Linux (musl)**: `fast-tts-cli-x86_64-unknown-linux-musl.tar.gz`
  - **macOS (Intel)**: `fast-tts-cli-x86_64-apple-darwin.tar.gz`
  - **macOS (Apple Silicon)**: `fast-tts-cli-aarch64-apple-darwin.tar.gz`
  - **Windows**: `fast-tts-cli-x86_64-pc-windows-msvc.zip`